apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}-service
  labels:
    app: {{ .Values.global.app }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
  selector:
    app: {{ .Values.global.app }}
    component: backend
