apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}
  labels:
    app: {{ .Values.global.app }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.app }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Values.global.app }}
        component: backend
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

          env:
            # הסיסמה של ה-DB (נשלף מה-Secret)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: DB_PASSWORD
                  
            # ה-Secret של ה-JWT (נשלף מה-Secret)
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: JWT_SECRET
                  
            # API Keys for external services
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: OPENAI_API_KEY
                  
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: TMDB_API_KEY