apiVersion: v1
kind: Secret
metadata:

  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Values.global.app }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:

  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "" | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "" | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | default "" | b64enc | quote }}
  TMDB_API_KEY: {{ .Values.secrets.tmdbApiKey | default "" | b64enc | quote }}
