apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Values.global.app }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: cG9zdGdyZXM=  # "postgres" encoded
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # "your-super-secret-jwt-key-change-this-in-production" encoded
  OPENAI_API_KEY: c2stcHJvai1SNjIwTDNyVWVGZDlfTmJLT1NrWVlsRXRwU0J6THVkOXJNdjBGYXVqTlJSUTBfNU1IZmtRbXFWTldnMG1rcVRSRV9TcFhDM281blQzQmxia0ZKSzhSMWY0TkJpeDFKMFBWcnhVOWhuQWx6TFl0c2F4Rk5TZ2Y4N0hiazNQcmVjVllESUZGb3otVzdLRGIxNGI3ZlNlMEp4eExBZ0E=
  TMDB_API_KEY: MWI0ZDlhMTljNjhjMGFjYWFkNGExZTc4NDI1MTU4NGY=
