# --- values.yaml ---
global:
  dbServiceName: "movie-db-service" 
  app: movie2

# ----------------------------------------
# 1. db settings
database:
  enabled: true
  image: "postgres:15" 
  volumeSize: "5Gi"   # גודל אחסון קבוע (PVC)
  port: 5432
  user: "postgres" # POSTGRES_USER
  name: "movie-db" # POSTGRES_DB

# ----------------------------------------
# 2. backend settings
backend:
  image: idanrachmany/movie2-backend:latest
  name: backend
  replicas: 2
  port: 5000
  env:
    DB_PORT: 5432
    NODE_ENV: development
    DB_HOST: movie-db-service
    JWT_EXPIRES_IN: "24h"

# ----------------------------------------
# 3. frontend settings
frontend:
  image: idanrachmany/movie2-frontend:latest
  name: frontend
  replicas: 3
  port: 3000
  apipath: "/api" # נתיב ה-API שאליו יפנה ה-frontend
  
# ----------------------------------------
# 4. Ingress settings
ingress:
  enabled: true
  host: "" # Empty host allows IP-based access
  className: "traefik"  # Changed to traefik to match your cluster
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web