apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" .Release.Name }}
  labels:
    app: {{ include "movie.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "movie.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "movie.name" . }}
        component: frontend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontend.targetPort }}
          env:
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.backend.port }}"
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          {{- if .Values.livenessProbe.frontend.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.frontend.path }}
              port: {{ .Values.livenessProbe.frontend.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.frontend.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.frontend.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.frontend.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.frontend.path }}
              port: {{ .Values.readinessProbe.frontend.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.frontend.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.frontend.periodSeconds }}
          {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
