apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-postgres" .Release.Name }}
  labels:
    app: {{ include "movie-charts.name" . }}
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "movie-charts.name" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "movie-charts.name" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "movie_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: init-script
          configMap:
            name: postgres-init
