apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" .Release.Name }}
  labels:
    app: {{ include "movie.name" . }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: {{ include "movie.name" . }}
    component: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http
